spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersql
    username: root
    password: 1025
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_